![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
np.__version__

<module 'numpy.version' from 'C:\\Users\\vscas\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [10]:
a = np.random.random(size=(3,2,5))

#### 4. Print *a*.


In [11]:
print(a)

[[[0.99053303 0.61528337 0.32661048 0.44974485 0.09370862]
  [0.01629961 0.23280533 0.77541375 0.68001751 0.48871813]]

 [[0.97973563 0.349848   0.15299633 0.04213288 0.34434335]
  [0.59960539 0.43250725 0.6340746  0.38997144 0.19800385]]

 [[0.17661761 0.54724019 0.46995646 0.05456184 0.63429369]
  [0.91840081 0.78725308 0.99216958 0.66132673 0.36263334]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [13]:
b = np.ones([5,2,3])

#### 6. Print *b*.


In [16]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
a.shape == b.shape

Possuem o mesmo tamanho


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
#Não é possível por causa das dimensões.
a + b

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.
*Hint: The tranpose of 5x2x3 is 3x2x5*

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [22]:
c = b.T

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [23]:
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [27]:
print(a)
print(' ---- ')
print(d)

[[[0.99053303 0.61528337 0.32661048 0.44974485 0.09370862]
  [0.01629961 0.23280533 0.77541375 0.68001751 0.48871813]]

 [[0.97973563 0.349848   0.15299633 0.04213288 0.34434335]
  [0.59960539 0.43250725 0.6340746  0.38997144 0.19800385]]

 [[0.17661761 0.54724019 0.46995646 0.05456184 0.63429369]
  [0.91840081 0.78725308 0.99216958 0.66132673 0.36263334]]]
 ---- 
[[[1.99053303 1.61528337 1.32661048 1.44974485 1.09370862]
  [1.01629961 1.23280533 1.77541375 1.68001751 1.48871813]]

 [[1.97973563 1.349848   1.15299633 1.04213288 1.34434335]
  [1.59960539 1.43250725 1.6340746  1.38997144 1.19800385]]

 [[1.17661761 1.54724019 1.46995646 1.05456184 1.63429369]
  [1.91840081 1.78725308 1.99216958 1.66132673 1.36263334]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [28]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [31]:
print(e)
print('''

----

''')
print(a)

[[[0.99053303 0.61528337 0.32661048 0.44974485 0.09370862]
  [0.01629961 0.23280533 0.77541375 0.68001751 0.48871813]]

 [[0.97973563 0.349848   0.15299633 0.04213288 0.34434335]
  [0.59960539 0.43250725 0.6340746  0.38997144 0.19800385]]

 [[0.17661761 0.54724019 0.46995646 0.05456184 0.63429369]
  [0.91840081 0.78725308 0.99216958 0.66132673 0.36263334]]]


----


[[[0.99053303 0.61528337 0.32661048 0.44974485 0.09370862]
  [0.01629961 0.23280533 0.77541375 0.68001751 0.48871813]]

 [[0.97973563 0.349848   0.15299633 0.04213288 0.34434335]
  [0.59960539 0.43250725 0.6340746  0.38997144 0.19800385]]

 [[0.17661761 0.54724019 0.46995646 0.05456184 0.63429369]
  [0.91840081 0.78725308 0.99216958 0.66132673 0.36263334]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f'Valor max: {d_max}')
print(f'Valor min: {d_min}')
print(f'Média: {d_mean}')

Valor max: 1.9921695834609143
Valor min: 1.01629961109085
Média: 1.4798935580947428


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 3x2x5) as *d* using `np.empty`.


In [53]:
f = np.empty([3,2,5])

AttributeError: 'numpy.ndarray' object has no attribute 'np'